<?php
namespace app\facade;
use think\Facade;

class Test extends Facade
{
    // 重写父类
    protected static function getFacadeClass()
    {
        //parent::getFacadeClass(); // TODO: Change the autogenerated stub
        // 绑定 app\common\Test 类
        return 'app\common\Test';
    }
}